ant-design/ant-design-mobile-rn

components/tag/PropsType.tsx, components/tag/__tests__/index.test.native.js, components/tag/demo/basic.native.tsx, components/tag/index.en-US.md, components/tag/index.native.tsx, components/tag/index.zh-CN.md
For this issue #20 
*isNewFeature* **:**
=> feat: Tag supports long press

components/carousel/demo/basic.native.tsx, components/carousel/index.native.tsx, components/carousel/index.zh-CN.md
For this issue #26 and fix the selectedIndex display error in issue #7 
*isNewFeature* **:**
=> feat: Carousel supports vertical

components/grid/index.native.tsx
=> Compute item height via column number property.

components/input-item/index.native.tsx
Hi guys input property editable was not working 👍 this is a little fix.
*isBugFix* **:**
* [] Make sure that you add at least one unit test for the bug which you had fixed.
=> fix bug input editable

components/button/index.native.tsx, components/list/PropsType.tsx
In this PR, I mainly change ButtonProps#activeStyle from `boolean` to `StyleProp<ViewStyle>`
https://github.com/ant-design/ant-design-mobile-rn/blob/71147f08b612bb258b8aa23e77e9c67c730a82fd/components/button/index.native.tsx#L18
It is because when I run this button demo, 
https://github.com/ant-design/ant-design-mobile-rn/blob/22603c21f1ac2c6399aec76bce0e47defb830bfc/components/button/demo/basic.native.tsx#L32
TSLint warns me that
```
不能将类型“{ backgroundColor: string; }”分配给类型“boolean | undefined”。
```
It's confusing and kind of a mistake.
So I make this PR.
BTW, I correct a little other related code.
=> optimize the definition of props with a more proper way

components/swipe-action/index.tsx
The default type defination of `SwipeAction` buttons is `?SwipeoutButtonProperties[]`, and there is no style property of SwipeoutButtonProperties.
So when I use literal object which has a style prop for right or left buttons, there will be an error: `Object literal may only specify known properties, and 'style' does not exist in type 'SwipeoutButtonProperties'`
Example:
```javascript
<SwipeAction
autoClose
style={{ backgroundColor: 'transparent' }}
right={[
{
text: 'More',
style: { backgroundColor: 'orange', color: 'white' }
},
{
text: 'Delete',
style: { backgroundColor: 'red', color: 'white' }
}
]}
>
<List.Item extra='extra content'>Simple example: left and right buttons</List.Item>
</SwipeAction>
```
=> fix SwipeAction props type defination about left and right

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/grid/index.en-US.md, components/grid/index.zh-CN.md, docs/react/upgrade-notes.en-US.md, docs/react/upgrade-notes.zh-CN.md
=> fix issue #233

components/modal/Modal.tsx, components/modal/index.tsx
fix #236 
set the `alert`,`prompt`,`operation` value of component `Modal` in `components/modal/index.tsx` instead of `components/modal/Modal.tsx` to avoid require cycle.
=> fix: remove react native require cycle warning

components/locale-provider/__tests__/__snapshots__/demo.test.js.snap, components/search-bar/__tests__/__snapshots__/demo.test.js.snap, components/search-bar/style/index.tsx, components/tab-bar/__tests__/__snapshots__/demo.test.js.snap
`SearchBar` icon size doesn't fit well, default size of the icon is `md` but height may be `xxs` and the component `Icon` doesn't use `width` or `height` to set icon size but `fontSize`.
=> fix search-bar icon size

components/tabs/Tabs.tsx
Fix [Type error when using Tabs (react-native: 0.59.x) #403](https://github.com/ant-design/ant-design-mobile-rn/issues/403)
=> use call fn to invoke scollView's scrollTo

components/picker/cascader/Cascader.tsx, components/picker/demo/basic.tsx
* [x ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
=> fix #412 and picker demo

components/segmented-control/PropsType.tsx, components/segmented-control/demo/basic.tsx, components/segmented-control/segmented.android.tsx
<p>&nbsp;&nbsp;The SegmentedControl component has a bug in Android because the selected segment text color is forced to be written as "#fff". When tintColor is set to "#fff", the selected segment text is invisible. The modified code can be used to set the current active text color via the style attribute. If not set, the default is "#fff". 
</p>
<p>&nbsp;&nbsp;SegmentedControl组件在安卓的情况下出现bug，原因是被选中的segment text颜色被强制写死成"#fff",在tintColor被设置为"#fff"的时候，被选中的segment文本看不见。修改过后的代码可以通过style属性来设置当前活跃文本颜色，如果没有设置的话默认为"#fff"。</p>
<p>ant-design-mobile-rn: 2.3.3</p>
<p>device: android phone</p>
<p>
import the SegmentedControl from ant-design-mobile-rn, and set the tintColor to “#fff”
</p>
<p>[Android] [Fixed] fix the selected segment bug in android</p>
<h1>Test Plan</h1>
- [ done] Edit the demo of this …
=> SegmentedControl comonent selected segment  text bug in android

docs/react/introduce.en-US.md, docs/react/introduce.zh-CN.md
=> 修改文档使用expo sdk32以上版本时出现的问题

components/modal/ModalView.tsx
> 有一些非我这边的改动导致的ts类型错误
```
antd-tools run compile
components\grid\index.tsx(91,33): error TS2345: Argument of type 'DataItem | undefined' is not assignable to parameter of type 'DataItem'.
Type 'undefined' is not assignable to type 'DataItem'.
components\image-picker\demo\basic.tsx(54,9): error TS2345: Argument of type '{ 'title': string; 'message': string; }' is not assignable to parameter of type 'Rationale'.
Property 'buttonPositive' is missing in type '{ 'title': string; 'message': string; }' but required in type 'Rationale'.
```
> 防止组件销毁后执行动画完成回调导致setState一个不存在的组件
> I Have no idea how to write this bug to …
=> Modal动画销毁前停止动画

components/grid/__tests__/__snapshots__/demo.test.js.snap, components/grid/index.tsx
Grid新的一行不满columnNum时，如果自定义了itemStyle，用来填充columnNum的item样式会和正常的item不一样的问题
比如自定义了itemStyle的height，该行被填充的item的height拉伸，导致和别的满columnNum的行不一致
=> Grid新的一行不满columnNum时，如果自定义了itemStyle，用来填充columnNum的item样式会和正常的item不一样的问题

components/list/ListItem.tsx
=> Add onLongPress to ListItem

components/date-picker-view/locale/pt_BR.tsx, components/date-picker/locale/pt_BR.tsx, components/input-item/locale/pt_BR.tsx, components/list-view/locale/pt_BR.tsx, components/locale-provider/demo/basic.md, components/locale-provider/demo/basic.tsx, components/locale-provider/pt_BR.tsx, components/modal/locale/pt_BR.tsx, components/pagination/locale/pt_BR.tsx, components/picker/locale/pt_BR.tsx, components/search-bar/locale/pt_BR.tsx
=> Include pt_BR translate

components/modal/Modal.tsx, components/modal/PromptContainer.tsx, components/modal/style/index.tsx
修改`Modal.tsx`样式，将`innerContainer`样式放在`<RCModal>`内，并由`KeyboardAvoidingView`包裹，而`<RCModal>`高度撑满并设置为透明，
以达到在`ios`中键盘呼出时(`Android`系统自带)，`innerContainer`图层有空间向上顶露出`TextInput`
⚠️注意：仅测试通过本地用例
=> fixs: https://github.com/ant-design/ant-design-mobile-rn/issues/722

components/result/index.tsx
修复Result组件没有指定buttonType时的错误
`TypeError: undefined is not an object (evaluating '_reactNative.StyleSheet.flatten(activeStyle ? activeStyle : _styles[type + 'Highlight']).backgroundColor')
`
=> remove Result defaultProps

components/list/style/index.tsx
不能将类型“{ fontSize: number; }”分配给类型“ViewStyle”
=> fix: Arrow type error

components/switch/__tests__/__snapshots__/demo.test.js.snap, components/switch/index.tsx, components/toast/__tests__/__snapshots__/demo.test.js.snap, components/toast/demo/basic.tsx, components/toast/index.en-US.md, components/toast/index.tsx, components/toast/index.zh-CN.md
https://github.com/ant-design/ant-design-mobile-rn/issues/899
- defaultConfig，Toast 默认参数
- config 方法，用于自定义 Toast 的默认参数，建议在 App 启动后调用
- getConfig 方法，用于获取当前配置
- content 参数支持传入对象，向后兼容的同时，支持新的参数
- stackable: 开启时，这条 Toast 会叠加在之前的 Toast 上；关闭时，弹出这条 Toast 前会清空其它 Toast。默认开启，建议开发者在生产环境下关闭，保证更好的用户体验。
- remove 方法，同 Portal.remove，对外隐藏 Portal 概念
- removeAll 方法，清空当前所有 Toast
- 修复文档中“一次只允许一个 Toast”这个不正确的描述
- 将文档中未提及的 show API 标记为 deprecated
- 修复文档中对于 hide 的相关描述
- 修复文档中 duration 默认值是 3s，但代码中是 2s 的问题
- Switch 使用 trackColor，消除 RN 的警告⚠️
=> feat: configurable toast

components/toast/index.tsx
去掉了错误的 `@depreacted` 使用，原来的写法会导致整个方法被标记为废弃。
=> fix: toast jsdoc

package.json, rn-kitchen-sink/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, rn-kitchen-sink/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
In checking out the development environment and starting dev on `form`, I came across an improvement and an error. I made a couple of minor additions/fixes.
During kitchen sink Android build (from react-native cli), an error was thrown: resource drawable/ic_launcher_background (aka com.kitchensink:drawable/ic_launcher_background) not found.
I attempted ./gradlew clean and problem was not on my end. If adaptive icon configuration was done through android studio previously and a file was excluded (or external) to the project, that could be the source of the error.
I rolled this back so kitchen sink android will build properly. I deleted the folder: ant-design-mobile-rn/rn-kitchen-sink/android/app/src/main/res/mipmap-anydpi-v26/
This is a very minor fix, not much is affected.
Currently, both …
=> Dev environment and rn-kitchen-sink fixes.

components/toast/ToastContainer.tsx, components/toast/demo/basic.tsx, components/toast/index.tsx
fix: 'Types of property 'content' are incompatible.' in Toast and add demo.
caused by this PR. [https://github.com/ant-design/ant-design-mobile-rn/pull/1160](https://github.com/ant-design/ant-design-mobile-rn/pull/1160)
Add test case for custom view in Toast.
=> fix: 'Types of property 'content' are incompatible.' in Toast and add demo

components/picker/style/index.tsx
make up for missing styles: `picker/Popup.tsx`
https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/Popup.tsx#L36
=> fix: picker continer style

components/pagination/style/index.tsx
=> fix: Pagination style

components/action-sheet/index.en-US.md, components/action-sheet/index.zh-CN.md
现`动作面板`文档中`api描述`不太完善
故按照其他组件的文档格式，完善了`动作面板`的`api描述`
=> docs: update the ActionSheet's docs

components/button/ButtonWave.tsx
不好意思新手没学会build。这是本地测试可修复问题的改动，仅供参考。查到的问题原因是TouchableNativeFeedback的children需要被View包裹住不然可能无法触发onPress
#1235
=> fix buttonwave on android cause checkbox can't be clicked

components/badge/index.tsx, components/modal/Modal.tsx, components/wing-blank/index.tsx
=> fix: type error on React 18

components/swipe-action/index.tsx
在 react-native-gesture-handler ^2.8.0 中
=> fix: 修复传入right视图不渲染或同时传入left、right，right渲染成left内容的问题

components/tabs/PropsType.tsx
This PR adds the ability to pass a React element into the Tabs element. For example :
```tsx
<Tabs>
<View>
<Text>Content of Third Tab</Text>
</View>
</Tabs>
```
=> fix: children as react element in tabs

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json
CHANGELOG
- fix: Picker support `numberOfLines` property [#1311](https://github.com/ant-design/ant-design-mobile-rn/issues/1311)
- fix: NativePicker.android.js support numberOfLines [~commit](https://github.com/ant-design/ant-design-mobile-rn/commit/f4505bbf291f12ec492489956ef34608e324af22)
- fix: Tabs `swipeable` work [#1305](https://github.com/ant-design/ant-design-mobile-rn/issues/1305)
- feat: gird replace Flex with View wrapper [~commit](https://github.com/ant-design/ant-design-mobile-rn/commit/a1dcf1c44ee505facdd6e7d8717710c61edc6f4f)
=> bump 5.0.5

components/notice-bar/notice-bar.tsx
`ref` should be added to `InnerNoticeBar` component even though it's not used. Otherwise, a warning will be thrown:
```
ERROR  Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
in App
in RCTView (created by View)
in View (created by AppContainer)
in RCTView (created by View)
in View (created by AppContainer)
in AppContainer
```
[issue link: https://github.com/ant-design/ant-design-mobile-rn/issues/1362](https://github.com/ant-design/ant-design-mobile-rn/issues/1362)
=> Fix forwardRef warning on InnerNoticeBar component

components/date-picker-view/date-picker-view.tsx, components/date-picker/date-picker.tsx
new Date() 解析如 2000-1-1时，不符合 ISO 8601 标准，react native会解析为NaN，修复后使用dayjs规范为ISO 8601 标准
=> fix: new Date not adhering to ISO 8601

components/tooltip/PropsType.tsx, components/tooltip/Tooltip.tsx, components/tooltip/index.en-US.md, components/tooltip/index.zh-CN.md
新增Tooltip属性crossOffset设置来解决弹窗位置偏移问题
=> feat: Add offset settings to tooltip

components/_util/hooks/useAnimations.tsx, components/accordion/__tests__/__snapshots__/demo.test.js.snap, components/checkbox/Checkbox.tsx, components/checkbox/__tests__/__snapshots__/demo.test.js.snap, components/checkbox/style/index.tsx, components/radio/__tests__/__snapshots__/demo.test.js.snap, components/radio/style/index.tsx
This PR fixes a bug in the checkbox component when using the `indeterminate` property with recent versions of react-native-reanimated.
- Renamed checkbox inner styles from 'after' to 'before'
- Updated animation logic for checkbox state transitions
- Fixed scale interpolation for indeterminate state
Fixes issue [#1430](https://github.com/ant-design/ant-design-mobile-rn/issues/1430)
Tested with Expo 53 and 52 on iOS and Android devices.
**Note:** This error only occurs in Expo 53 environments.
=> Fix Checkbox Indeterminate State Error
