- components/input-item/index.en-US.md
- components/input-item/index.zh-CN.md
> update doc: No `disabled` property.

- components/segmented-control/segmented.android.tsx
- package.json
> Replace with normalize-css-color

- components/button/index.native.tsx
* [ x Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
> 修复Button组件activeStyle属性为对象时不起作用的问题

- components/locale-provider/en_US.tsx
- components/locale-provider/locale-provider.tsx
- components/locale-provider/ru_RU.tsx
- components/locale-provider/sv_SE.tsx
- components/modal/Modal.native.tsx
- components/modal/PromptContainer.native.tsx
- components/modal/PropsType.tsx
- components/modal/locale/en_US.tsx
- components/modal/locale/ru_RU.tsx
- components/modal/locale/sv_SE.tsx
- components/modal/locale/zh_CN.tsx
Added locale for Modal component,
> Added locale for Modal component

- components/image-picker/PropsType.tsx
- components/image-picker/index.en-US.md
- components/image-picker/index.zh-CN.md
FYI: I didn't add the `styles` prop on the Chinese documentation as I don't speak Cantonese. Feel free to add it
> Fix #73 - ImagePicker prop types

- components/input-item/index.en-US.md
- components/input-item/index.zh-CN.md
- components/textarea-item/index.en-US.md
- components/textarea-item/index.zh-CN.md
> fix components docs

- components/tabs/PropsType.tsx
- components/tabs/Tabs.tsx
> add renderTab prop-type of tabs.

- components/list-view/index.tsx
> fix ListView loadmore issue with paginationAllLoadedView

- components/segmented-control/segmented.android.tsx
- components/segmented-control/segmented.ios.tsx
> 修改SegmentedControl默认颜色为主题颜色

- components/segmented-control/segmented.android.tsx
- components/segmented-control/segmented.ios.tsx
- package.json
> Segmented control tintcolor

- components/swipe-action/index.tsx
> fix: spread SwipeAction rest props

- components/card/CardHeader.tsx
- components/card/__tests__/__snapshots__/demo.test.js.snap
- components/card/style/index.tsx
> 为Card组件的HeaderContent和HeaderExtra添加Wrap style，便于定制

- components/textarea-item/index.tsx
> fixes:https://github.com/ant-design/ant-design-mobile-rn/issues/536

- components/date-picker/index.tsx
> fix DatePicker styles prop covering the context styles of WithTheme

- components/drawer/index.en-US.md
> English typo

- components/modal/Modal.tsx
修复modal footer的actions数量为奇数时, onFooterLayout 死循环调用导致整个footer会不停地上下抖动的问题
> fix: 修复modal footer上下抖动的问题

- components/picker/PopupMixin.tsx
> fixs bug: "Name in a signature must be an Identifier"

- components/input-item/PropsType.tsx
> 修复InputItem的textAlign属性没有right值的问题

- components/modal/AlertContainer.tsx
- components/modal/Modal.tsx
- components/modal/ModalView.tsx
- components/modal/OperationContainer.tsx
- components/modal/PromptContainer.tsx
- components/modal/index.en-US.md
- components/modal/index.zh-CN.md
> fixes: #773

- .prettierrc
- components/carousel/__tests__/__snapshots__/demo.test.js.snap
- components/carousel/__tests__/index.test.js
- components/carousel/demo/basic.tsx
- components/carousel/index.en-US.md
- components/carousel/index.tsx
- components/carousel/index.zh-CN.md
- components/grid/__tests__/__snapshots__/demo.test.js.snap
- package.json
- rn-kitchen-sink/App.js
> refactor: using ViewPager

- components/popover/__tests__/__snapshots__/demo.test.js.snap
- components/popover/demo/basic.tsx
- components/popover/index.en-US.md
- components/popover/index.tsx
- components/popover/index.zh-CN.md
https://github.com/ant-design/ant-design-mobile-rn/issues/857
> feat: customize popover animation

- components/modal/Modal.tsx
* [x ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
> fix: 修复部分Android机型 modal footer 无限抖动的问题

- components/date-picker-view/locale/es_ES.tsx
- components/date-picker/datepicker/locale/es_ES.tsx
- components/date-picker/locale/es_ES.tsx
- components/list-view/locale/es_ES.tsx
- components/locale-provider/es_ES.tsx
- components/modal/locale/es_ES.tsx
> Fix es_ES locale

- components/notice-bar/Marquee.tsx
如题，使用`transform[]`替换`left`、`right`、`top`、`bottom`位移动画
建议检查所有`Animated`相关组件并重构👀
> fix: Animated replace "translateX" to "left" (#974)

- components/steps/style/index.tsx
> 修复步骤条的进度线不能自适应步骤的详情描述的高度问题

- __mocks__/@react-native-community/async-storage.js
- components/toast/index.tsx
> fix: toast remove

- components/date-picker-view/date-picker-view.tsx
- components/date-picker/index.tsx
- components/list-view/index.tsx
- components/locale-provider/index.tsx
- components/modal/Modal.tsx
- components/modal/PromptContainer.tsx
- components/pagination/index.tsx
- components/picker/index.tsx
- components/search-bar/index.tsx
issue link: https://github.com/ant-design/ant-design-mobile-rn/issues/1093
> pref: 国际化组件LocaleProvider优化提案

- components/date-picker-view/locale/fa_IR.tsx
- components/date-picker/locale/fa_IR.tsx
- components/input-item/locale/fa_IR.tsx
- components/list-view/locale/fa_IR.tsx
- components/locale-provider/fa_IR.tsx
- components/modal/locale/fa_IR.tsx
- components/pagination/locale/fa_IR.tsx
- components/picker/locale/fa_IR.tsx
- components/search-bar/locale/fa_IR.tsx
> add persian locale

- components/carousel/index.tsx
- components/carousel/style/index.tsx
> feat(carousel): add new property: wrapperStyle

- components/date-picker/datepicker/DatePickerProps.tsx
- components/picker-view/PickerView.tsx
- components/picker/PickerTypes.tsx
- components/picker/PropsType.tsx
- components/picker/cascader/CascaderTypes.tsx
参考文档：https://github.com/react-native-picker/picker#itemstyle
> fix: picker itemStyle 类型错误，ViewStyle -> TextStyle

- components/action-sheet/AndroidContainer.tsx
- components/action-sheet/style/index.tsx
1. Make theme configurable for action-sheet/AndroidContainer
2. Remove action-sheet/style unneccessary comments
> fix: action-sheet for Android respects theme

- components/flex/FlexItem.tsx
> feat: support flex 0 in FlexItem to handle fixed width of some Items

- components/date-picker/PropsType.tsx
> fix: DatePickerPropsType interface add onOk

- components/toast/ToastContainer.tsx
- components/toast/demo/basic.tsx
fix #1196 #1195. 
`npm run lint` 先暂时跳过了，因为有些原有的代码也没满足这个lint，这个PR暂时先不修原有lint的问题了。
> fix: Toast onClose callback not called when removeAll.

- README.md
- README.zh-CN.md
> docs: add pod install in docs when `start ios`

- components/list-view/index.tsx
> fix(list-view): typings

- components/carousel/index.tsx
Refactor Carousel:
Fix:
CheckList:
> feat: refactor Carousel

- components/carousel/index.tsx
- components/tabs/DefaultTabBar.tsx
- components/tabs/Tabs.tsx
- components/tabs/demo/basic.tsx
> feat: refactor Tabs

- components/action-sheet/index.native.tsx
- components/action-sheet/index.tsx
- components/action-sheet/style/index.tsx
> feat: ActionSheet create index.native.tsx

- components/button/__tests__/__snapshots__/demo.test.js.snap
- components/button/demo/basic.md
- components/button/demo/basic.tsx
- components/button/index.tsx
- components/carousel/__tests__/__snapshots__/demo.test.js.snap
- components/carousel/demo/basic.tsx
- components/modal/__tests__/__snapshots__/demo.test.js.snap
This PR adds the ability to pass a React element into the Button element.
For exemple :
```tsx
<Button type="primary">
<Icon name="login" />
</Button>
```
> feat: children as react element in button

- docs/react/introduce.en-US.md
- docs/react/introduce.zh-CN.md
> docs: about link

- components/swipe-action/index.en-US.md
The spelling of "operation" was "opration" in this file.
> Fixed the spelling of "operation" in SwipeAction component.

- components/slider/index.en-US.md
> Fix typo in Slider Documentation

- components/date-picker-view/locale/ko_KR.tsx
- components/date-picker/datepicker/locale/ko_KR.tsx
- components/date-picker/locale/ko_KR.tsx
- components/input-item/locale/ko_KR.tsx
- components/list-view/locale/ko_KR.tsx
- components/locale-provider/ko_KR.tsx
- components/modal/locale/ko_KR.tsx
- components/pagination/locale/ko_KR.tsx
- components/picker/locale/ko_KR.tsx
- components/search-bar/locale/ko_KR.tsx
> Add: locale ko-KR 한국어 추가

- components/grid/PropsType.tsx
Gird onPress 2th paramter should be optional,  we do not need `itemIndex` some times.
> TS: function parameter should be optional.

- components/button/index.tsx
- components/modal/ModalView.tsx
- package.json
- yarn.lock
issue: https://github.com/ant-design/ant-design-mobile-rn/issues/1416
> feat: change the BackHandler usage for  react-native 0.67 version

- components/tooltip/style/index.tsx
In the `Tooltip` component, borders are styled using the `borderColor` property, which limits the ability to individually customize each border. This prevents the implementation of more complex designs where different borders need different colors.
Currently, the Tooltip arrow style is defined with a single `borderColor` property, which doesn't allow for individual border customization:
```tsx
arrow: {
width: 0,
height: 0,
borderColor: 'transparent',
borderStyle: 'solid',
borderWidth: theme.tooltip_arrow_size,
position: 'absolute',
},
```
Replace the `borderColor` property with individual border color properties:
```tsx
arrow: {
width: 0,
height: 0,
borderTopColor: 'transparent',
borderRightColor: 'transparent',
borderBottomColor: 'transparent',
borderLeftColor: 'transparent', …
```
> fix: update arrow border styles to ensure proper styling

- components/input/Input.tsx
- components/input/TextArea/index.tsx
> fix: issue 1431 & issue 1432
